export const PROCESSING_PARALLEL_MIN = 8;
export const PROCESSING_PARALLEL_MAX = 16;
export const DEFAULT_HARDWARE_CONCURRENCY = 4;

export const PROCESSING_WEBP_QUALITY = 0.82;

export const DEFAULT_MERGE_BATCH_SIZE = 10;
export const ZIP_DOWNLOAD_BATCH_SIZE = 50;

export const PROGRESS_UPDATE_INTERVAL_MS = 500;
export const PROGRESS_UPDATE_FRAME_INTERVAL = 50;
